[versions]
arrow = "1.2.1"
junit = "5.10.0"
kotest = "5.7.2"
kotestArrow = "1.3.3"
# @pin
kotlin = "1.7.22"
kotlinBinaryCompatibilityPlugin = "0.13.2"
mavenPublishGradlePlugin = "0.25.3"
versionCatalogUpdateGradlePlugin = "0.8.1"
versionsGradlePlugin = "0.48.0"

[libraries]
arrowCore = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrowResilience = { module = "io.arrow-kt:arrow-resilience", version.ref = "arrow" }
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestAssertionsArrow = { module = "io.kotest.extensions:kotest-assertions-arrow", version.ref = "kotestArrow" }
kotestFrameworkApi = { module = "io.kotest:kotest-framework-api", version.ref = "kotest" }
kotestJunitRunnerJvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotestProperty = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotestPropertyArrow = { module = "io.kotest.extensions:kotest-property-arrow", version.ref = "kotestArrow" }

[bundles]
kotest = [
    "kotestAssertions",
    "kotestAssertionsArrow",
    "kotestFrameworkApi",
    "kotestJunitRunnerJvm",
    "kotestProperty",
    "kotestPropertyArrow",
]

[plugins]
dokka = "org.jetbrains.dokka:1.9.0"
kotlinBinaryCompatibilityPlugin = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBinaryCompatibilityPlugin" }
kotlinGradlePlugin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublishGradlePlugin = { id = "com.vanniktech.maven.publish.base", version.ref = "mavenPublishGradlePlugin" }
versionCatalogUpdateGradlePlugin = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdateGradlePlugin" }
versionsGradlePlugin = { id = "com.github.ben-manes.versions", version.ref = "versionsGradlePlugin" }
